secrets:
  client.certificate:
    file: ${CLIENT_CERT_PATH}
  client.key:
    file: ${CLIENT_KEY_PATH}

services:
  client:
    build:
      context: client/
    restart: unless-stopped
    ports:
      - target: 443
        published: 443
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - source: client.certificate
        target: /certs/fullchain.pem
      - source: client.key
        target: /certs/privkey.pem
    ulimits:
      nofile:
        soft: 15000
        hard: 15000

  api:
    build:
      context: api/
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    ulimits:
      nofile:
        soft: 15000
        hard: 15000
